/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jeno.javaparsertest;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.type.ReferenceType;

public class App {

	private static final ReferenceType LIST = JavaParser.parseClassOrInterfaceType("List<java.util.Map<String, Object>>");

	public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
